spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: auth
  redis:
    host: redis
  data:
    mongodb:
      database: auth
      host: mongo-auth

server:
  servlet:
    context-path: /uaa
  port: 8001